### ISSUE TITLE
Cannot discover OCF server that built from development flow

### ISSUE THREAD

**Issue by liz7124** [openconnectivity/otgc-linux#20]
Hi.
I built the Iotivity/OCF Server with 2 ways:
First, from here https://github.com/iotivity/iotivity-lite. I used MAKE and ran the simpleserver file. Then, I used OTGC-linux to discover the server. It worked and I could discover the OCF server (simpleserver). But, when I ran OTGC-android to discover the server, it won't work. Couldn't found the server (simpleserver).

Second, from here https://github.com/openconnectivity/IOTivity-Lite-setup. I followed the development flow: build, gen, reset, run. I used the enviro-phat example.
But, when I ran the OTGC-linux to discover the server, it couldn't found the server (enviro-phat). So, I tried ran the OTGC-android, it worked and can discover the enviro-phat as OCF server.

Why the second way OTGC-linux couldn't discover the server? Because I want to build OCF server with second way and want to use OTGC-linux as a OCF client.

Thanks.

**Comment by cstevens** [comment]
Elizabeth,

I have had similar results when I am running linux as a virtual machine on my Mac. Your symptoms sound like your missing devices are on a different network. I’m not sure why this happens to me, because the server and the client look like they’re on the same segment, but something weird is happening. I seem to have no problem when I have Android discovering Raspberry Pi on the same network, but it can’t see my virtual device on linux on my VM. Similarly, OTGC_linux on my VM can see the emulated device on linux, but not the Raspberry Pi or Android OTGC.

I’m not certain this is your issue, but it seems similar to my problem. I want to test this with a real linux computer rather than just a VM, but my real linux machine just died.

Thanks,
-Clarke

On Feb 12, 2020, at 10:11 AM, Elizabeth Nathania W <notifications@github.com<mailto:notifications@github.com>> wrote:


  CAUTION: This email is from an external source. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi.
I built the Iotivity/OCF Server with 2 ways:
First, from here https://github.com/iotivity/iotivity-lite. I used MAKE and ran the simpleserver file. Then, I used OTGC-linux to discover the server. It worked and I could discover the OCF server (simpleserver). But, when I ran OTGC-android to discover the server, it won't work. Couldn't found the server (simpleserver).

Second, from here https://github.com/openconnectivity/IOTivity-Lite-setup. I followed the development flow: build, gen, reset, run. I used the enviro-phat example.
But, when I ran the OTGC-linux to discover the server, it couldn't found the server (enviro-phat). So, I tried ran the OTGC-android, it worked and can discover the enviro-phat as OCF server.

Why the second way OTGC-linux couldn't discover the server? Because I want to build OCF server with second way and want to use OTGC-linux as a OCF client.

Thanks.

**Comment by liz7124** [comment]
Hi Clarke,
Yes, for my case I was ran linux as VM too on my Windows. And I just try on my linux machine and it works. For now I will just use on my linux machine. Thanks.
But sorry I can't help debug why if run linux as VM can't discover the devices.

Also, I want to ask what is the different OBT mode and Client mode? It seems in Client mode I can't onboard my devices.

**Comment by cstevens** [comment]
I’m glad that was the problem and also the you have a separate linux machine. Out of curiosity, which VM were you using. I use VMWare Fusion. I’d like to figure out if this problem is due to a specific vendor or if it happens on all VMs. I have tried bridge mode (which should make it indistinguishable from an standalone machine as well as NAT mode (which I would expect not to work). It doesn’t work for me in either mode or either direction.

As for Client mode, I would have to go back and look at the use case, but I seem to recall that it is used to share the control of a single server from multiple clients (e.g. each client app in your home could control the same light).

Thanks,
-Clarke

On Feb 12, 2020, at 8:09 PM, Elizabeth Nathania W <notifications@github.com<mailto:notifications@github.com>> wrote:


  CAUTION: This email is from an external source. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi Clarke,
Yes, for my case I was ran linux as VM too on my Windows. And I just try on my linux machine and it works. For now I will just use on my linux machine. Thanks.
But sorry I can't help debug why if run linux as VM can't discover the devices.

Also, I want to ask what is the different OBT mode and Client mode? It seems in Client mode I can't onboard my devices.

**Comment by liz7124** [comment]
Actually not really separate, because I use 1 machine with dual boot OS (windows+linux).
For the VM I use VMWare Workstation 15 for Windows.

But for the OTGC-linux, after I onboarding my devices with OBT mode, then change to Client mode I couldn't connect to my device, even it's discovered. Then, when I click Onboard, it said only OBT mode can do onboarding.

**Comment by cstevens** [comment]
Elizabeth,

So maybe network issue is a VMWare problem since we are both using VMWare.

With the client mode, I think that is right. You have to use OBT mode to onboard another device. I think if you wanted to add a client to your household (say for a spouse), he would put his OTGC in client mode and you would then onboard it and he could control the servers in your household as well. NOTE: I am not sure of the exact process. There are two ways to do it and I haven’t done it for several months, so I would have to review.

Thanks,
-Clarke

On Feb 12, 2020, at 11:13 PM, Elizabeth Nathania W <notifications@github.com<mailto:notifications@github.com>> wrote:


  CAUTION: This email is from an external source. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Actually not really separate, because I use 1 machine with dual boot OS (windows+linux).
For the VM I use VMWare Workstation 15 for Windows.

But for the OTGC-linux, after I onboarding my devices with OBT mode, then change to Client mode I couldn't connect to my device, even it's discovered. Then, when I click Onboard, it said only OBT mode can do onboarding.

**Comment by WAvdBeek** [comment]
There is an option in VMWare to enable multicast. default the multicast is disabled.
not sure where this is in the UI though.
